project_name: srcdsup

builds:
  - id: srcdsup
    env: [CGO_ENABLED=0]
    goos:
      - linux
      - windows
    goarch:
      - amd64
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}} -X main.builtBy=releaser

nfpms:
  - maintainer: Leigh MacDonald <leigh.macdonald@gmail.com>
    description: Auto upload files from remote servers to gbans
    homepage: https://github.com/leighmacdonald/srcdsup
    license: MIT
    formats:
      - deb
      - rpm
      - apk

archives:
  - builds:
      - srcdsup
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    files:
      - LICENSE.md
      - README.md
      - srcdsup_example.yml
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

release:
  github:
    owner: leighmacdonald
    name: srcdsup
  draft: true
  replace_existing_draft: true
  prerelease: auto

changelog:
  use: github-native

signs:
  - artifacts: checksum
    args:
      - "--batch"
      - "-u"
      - "{{ .Env.GPG_FINGERPRINT }}"
      - "--output"
      - "${signature}"
      - "--detach-sign"
      - "${artifact}"

announce:
  discord:
    enabled: true
    message_template: 'srcdsup {{.Tag}} is out!'

    # Set author of the embed.
    # Defaults to `GoReleaser`
    author: 'Leigh MacDonald'
    # color: ''

    # URL to an image to use as the icon for the embed.
    # Defaults to `https://goreleaser.com/static/avatar.png`
    # icon_url: ''

# yaml-language-server: $schema=https://goreleaser.com/static/schema-pro.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj
